### PR TITLE
(#105) add enum: DW_OP_LLVM_convert

### PR DESCRIPTION
**Pull request by dannypsnl**
approach commands

```
go generate ./...
cd asm/enum && make
```

issue: still can't fix the bug https://github.com/llir/llvm/issues/105#issuecomment-558913705

### CODE REVIEW

**Comment by mewmew** [comment]
Thanks @dannypsnl, looks good to me.

Would you run `goimports -w *.go` in `asm/enum`? (This is done automatically when running `make` from the `asm/enum` directory)

You've added almost all new `DW_OP` enums. There is one more in `llvm-9.0.0.src/include/llvm/BinaryFormat/Dwarf.h`, namely `DW_OP_LLVM_tag_offset = 0x1002`.

```cpp
enum LocationAtom {
#define HANDLE_DW_OP(ID, NAME, VERSION, VENDOR) DW_OP_##NAME = ID,
#include "llvm/BinaryFormat/Dwarf.def"
  DW_OP_lo_user = 0xe0,
  DW_OP_hi_user = 0xff,
  DW_OP_LLVM_fragment = 0x1000,   ///< Only used in LLVM metadata.
  DW_OP_LLVM_convert = 0x1001,    ///< Only used in LLVM metadata.
  DW_OP_LLVM_tag_offset = 0x1002, ///< Only used in LLVM metadata.
};
```

There is also one more `DW_OP` enum added in LLVM 9.0, and it is located in `llvm-9.0.0.src/include/llvm/BinaryFormat/Dwarf.def` (notice the `#include "llvm/BinaryFormat/Dwarf.def"` line above), namely `DW_OP_GNU_entry_value = 0xf3`.

Relevant results from running `diff -u llvm-{7,9}.0.0.src/include/llvm/BinaryFormat/Dwarf.def`

```diff
+// The GNU entry value extension.
+HANDLE_DW_OP(0xf3, GNU_entry_value, 0, GNU)
```

Would you update the PR to include these two enums @dannypsnl?

```cpp
DW_OP_LLVM_tag_offset = 0x1002
DW_OP_GNU_entry_value = 0xf3
```

Cheers,
Robin

**Comment by mewmew** [comment]
With your patch applied, we currently fail at:

```
--- FAIL: TestParseFile (0.24s)
panic: unable to locate DwarfOp enum corresponding to "DW_OP_LLVM_tag_offset" [recovered]
	panic: unable to locate DwarfOp enum corresponding to "DW_OP_LLVM_tag_offset"
```

Which is from line 25 of [llvm/test/Assembler/diexpression.ll](https://github.com/llir/testdata/blob/3c4d1a35ba23daf6e161d060feffadfc518a5215/llvm/test/Assembler/diexpression.ll#L25):

```llvm
!8 = !DIExpression(DW_OP_LLVM_tag_offset, 1)
```

**Comment by dannypsnl** [comment]
Thanks, now I know-how to debug texmapper and find new enum. I would update
them later.

**Comment by dannypsnl** [comment]
I found that `goimports -w *.go` would change the `import (...)` to `import a; import b` now. I would take a look at how to fix this behavior.

**Comment by mewmew** [comment]
> I found that goimports -w *.go would change the import (...) to import a; import b now. I would take a look at how to fix this behavior.

Oh, that's interesting. What version of `goimports` are you using?

**Comment by mewmew** [comment]
P.S, I'm sending a fix for the `*ast.DwarfAttEncoding` handling.

**Comment by mewmew** [comment]
As `DwarfAttEncoding` is now a valid `DIExpressionField`, we needed to update the AST to IR converter. This was done in commit: https://github.com/llir/llvm/commit/5a787c497c0409c2dce71a00e7199287341fad00

**Comment by mewmew** [comment]
@dannypsnl, once we figure out the issue with `goimports`, then after merging this PR, all current test cases will be passing again. Thanks a lot for the help!

**Comment by mewmew** [comment]
With `goimports` from golang/tools@ecd32218bd7f33fd31c1abbfb74283690bedd093, I get the correct output:

```diff
diff --git a/asm/enum/atomicop_string2enum.go b/asm/enum/atomicop_string2enum.go
index 77303e0..824e0b4 100644
--- a/asm/enum/atomicop_string2enum.go
+++ b/asm/enum/atomicop_string2enum.go
@@ -2,8 +2,11 @@
 
 package enum
 
-import "fmt"
-import "github.com/llir/llvm/ir/enum"
+import (
+       "fmt"
+
+       "github.com/llir/llvm/ir/enum"
+)
```

**Pull request merged**
