### PR TITLE
(#128) new calling conventions

### PR DESCRIPTION
**Pull request by dannypsnl**
- [x] update ll in go.mod

The only weird thing is I have no idea where `cfguard_checkcc` defined in [C++ header](https://llvm.org/doxygen/namespacellvm_1_1CallingConv.html). It should up to date v10 but no `guard`, `check` or `cf` word existed.

### CODE REVIEW

**Comment by mewmew** [comment]
Looks like the keyword is defined in `lib/AsmParser/LLToken.h`.
```cpp
$ llvm-10.0.0.src> ack cfguard_checkcc
lib/AsmParser/LLLexer.cpp:  KEYWORD(cfguard_checkcc);
lib/AsmParser/LLToken.h:  kw_cfguard_checkcc,
lib/AsmParser/LLParser.cpp:  case lltok::kw_cfguard_checkcc: CC = CallingConv::CFGuard_Check; break;
```

And the corresponding calling convention enum is defined in `include/llvm/IR/CallingConv.h`:

```cpp
$ llvm-10.0.0.src> ack CFGuard_Check
include/llvm/IR/CallingConv.h:    CFGuard_Check = 19,
```

**Comment by dannypsnl** [comment]
> Looks like the keyword is defined in `lib/AsmParser/LLToken.h`.
> 
> ```c++
> $ llvm-10.0.0.src> ack cfguard_checkcc
> lib/AsmParser/LLLexer.cpp:  KEYWORD(cfguard_checkcc);
> lib/AsmParser/LLToken.h:  kw_cfguard_checkcc,
> lib/AsmParser/LLParser.cpp:  case lltok::kw_cfguard_checkcc: CC = CallingConv::CFGuard_Check; break;
> ```
> 
> And the corresponding calling convention enum is defined in `include/llvm/IR/CallingConv.h`:
> 
> ```c++
> $ llvm-10.0.0.src> ack CFGuard_Check
> include/llvm/IR/CallingConv.h:    CFGuard_Check = 19,
> ```

Just fixed! Hope this PR pass all checks.

**Comment by dannypsnl** [comment]
current failure:

```
--- FAIL: TestParseFile (34.25s)
    asm_test.go:531: module "../testdata/llvm/test/Bitcode/calling-conventions.3.2.ll.golden" mismatch (-want +got):
          strings.Join({
          	... // 4 identical lines
          	"declare coldcc void @coldcc()",
          	"",
        - 	"declare cc10 void @cc10()",
        + 	"declare ghccc void @cc10()",
          	"",
          	"declare spir_kernel void @spir_kernel()",
          	... // 41 identical lines
          	"}",
          	"",
        - 	"define void @call_cc10 () {",
        + 	"define void @call_cc10() {",
          	"0:",
        - 	`	call cc10 void @cc10 ()`,
        + 	`	call ghccc void @cc10()`,
          	`	ret void`,
          	"}",
          	... // 79 identical lines
          }, "\n")
    asm_test.go:531: module "../testdata/llvm/test/CodeGen/X86/tailccfp.ll.golden" mismatch (-want +got):
          strings.Join({
        - 	"define tailcc i32 @bar(i32 %X, i32(double, i32) *%FP) {",
        + 	"define tailcc i32 @bar(i32 %X, i32 (double, i32)* %FP) {",
          	"0:",
          	`	%Y = tail call tailcc i32 %FP(double 0.0, i32 %X)`,
          	... // 3 identical lines
          }, "\n")
```

**Comment by mewmew** [comment]
> current failure:

Thanks! I'll update the golden output. When a calling convention is known by name it should be output by name (not `cc 10`). Also, there was a whitespace diff.

**Comment by mewmew** [comment]
With https://github.com/llir/testdata/commit/ce34acb55676e65bfc2a22bebfc4a4485ba58494 applied, all test cases are passing! :)

Really great job @dannypsnl!

```
llir/llvm (new-call-conv)> go test ./...
ok  	github.com/llir/llvm/asm	44.946s
?   	github.com/llir/llvm/asm/enum	[no test files]
?   	github.com/llir/llvm/cmd/l-ir	[no test files]
?   	github.com/llir/llvm/cmd/l-tm	[no test files]
?   	github.com/llir/llvm/cmd/l-tm2	[no test files]
ok  	github.com/llir/llvm/internal/enc	0.033s
?   	github.com/llir/llvm/internal/gep	[no test files]
ok  	github.com/llir/llvm/internal/natsort	0.058s
?   	github.com/llir/llvm/internal/osutil	[no test files]
ok  	github.com/llir/llvm/ir	0.552s
ok  	github.com/llir/llvm/ir/constant	2.335s
?   	github.com/llir/llvm/ir/enum	[no test files]
ok  	github.com/llir/llvm/ir/metadata	0.486s
ok  	github.com/llir/llvm/ir/types	0.008s
?   	github.com/llir/llvm/ir/value	[no test files]
```

**Pull request merged**
