### PR TITLE
(#88) fix *ir.Param attribute missing

### LINKED ISSUE #88: How to emit `nonnull` as a parameter attribute?
Came across an LLVM IR line that (so far) I've not been able to generate identically using `llir/llvm`:

```
tail call fastcc void %8(i8* nonnull %0), !dbg !33
```

The `nonnull` there doesn't seem to emit.  eg:

```
foo := ir.NewParam("", types.I8Ptr)
foo.Attrs = []ir.ParamAttribute{enum.ParamAttrNonNull}
someCall := ifThenIBlock.NewCall(val8, foo)  // val8() is already defined in earlier code
someCall.Tail = enum.TailTail
someCall.CallingConv = enum.CallingConvFast
someCall.Metadata = append(someCall.Metadata, &metadata.Attachment{Name: "dbg", Node: dbgLoc["33"]})
```

Sill emits:

```
tail call fastcc void %8(i8* %0), !dbg !33
```

Any ideas?

Kind of suspecting a bug, but not sure yet. :wink:

### PR DESCRIPTION
**Pull request by dannypsnl**
Fixes #88.

### CODE REVIEW

**Comment by justinclift** [comment]
Awesome @dannypsnl, thanks heaps.

I'll try this out (probably) later on today or tonight. :smile:

**Comment by mewmew** [comment]
Thanks @dannypsnl! The change looks good to me. Before merging, I think we should try to figure out why the test cases are failing, and see if we can update them to make the CI happy.

I would look at it, but right now I'm in the midst of studying for final exams. Should have more time in a week or two.

Cheers,
Robin

**Comment by dannypsnl** [comment]
Just rebased, I check the CI obviously is because of the test do not expect the attribute generated code, but run `go test ./... -count 1` at local is fine, pretty weird, does `ci_checks.sh` to more?

**Comment by justinclift** [comment]
Skimming over the logs, it's showing entries like this:

```
-	call void @llvm.dbg.value(metadata i8* %0, metadata !1162, metadata !DIExpression()), !dbg !1163
-	%2 = tail call i32 @strcmp(i8* %0, i8* getelementptr inbounds ([2 x i8], [2 x i8]* @.str.54, i64 0, i64 0)) #14, !dbg !1164
+	call void @llvm.dbg.value(metadata i8* nocapture readonly %0, metadata !1162, metadata !DIExpression()), !dbg !1163
+	%2 = tail call i32 @strcmp(i8* nocapture readonly %0, i8* getelementptr inbounds ([2 x i8], [2 x i8]* @.str.54, i64 0, i64 
```

eg `nocapture readonly` is now being emitted, which seems like the right kind of thing.

Guess the test cases need updating so they have the new strings included?

**Comment by justinclift** [comment]
In testing just now, this PR fixes the problem in #88. :smile:

**Comment by justinclift** [comment]
On second thoughts, the solution here might need a bit more work.

For example, some parameter attributes should be shown in function definitions like this:

```
define i8* @memset(i8* nocapture returned, i8, i32) local_unnamed_addr { stuff }
param0.Attrs = []ir.ParamAttribute{enum.ParamAttrNoCapture, enum.ParamAttrReturned}
```

But the same parameter when now included in `Call` lines breaks things.  For example, a call that should look like this:

    call void @llvm.dbg.value(metadata i8* %0, metadata !76, metadata !DIExpression())

Is now printed as:

    call void @llvm.dbg.value(metadata i8* nocapture returned %0, metadata !76, metadata !DIExpression())

The `nocapture returned` there break things when `llvm` utilities attempt to parse it:

```
$ clang --compile stuff.ll 
stuff.ll:85:41: error: expected value token
        call void @llvm.dbg.value(metadata i8* nocapture returned %0, metadata !76, metadata !DIExpression()), !dbg !79
                                               ^
```

Maybe `String()` will need to check what it's being called by?

**Comment by dannypsnl** [comment]
Does that is caused by attributes or llvm.dbg.value this function? I mean it's because of we should not print nocapture or we should not print nocapture when we call llvm.dbg.value?

That would be totally different level issue I guess.

**Comment by justinclift** [comment]
Not sure yet.  Will investigate tomorrow. :smile:

**Comment by mewmew** [comment]
> On second thoughts, the solution here might need a bit more work.

Yeah. You are right. We need to figure out what attributes are supposed to be printed, and when.

In general, the IR package has followed this rationale. Use `String()` when printing values being used in instructions, and use `LLString()` when printing the definition of values, e.g. when used in function declarations or definitions.

If we look at the definition of `ir.Param.LLString` we can see that it already prints attributes.

From https://github.com/llir/llvm/blob/c5c443dc6bf6217b0b5619d4f242e373dc3c6977/ir/helper.go#L377:

```go
// LLString returns the LLVM syntax representation of the function parameter.
func (p *Param) LLString() string {
	// Typ=Type Attrs=ParamAttribute* Name=LocalIdent?
	buf := &strings.Builder{}
	buf.WriteString(p.Typ.String())
	for _, attr := range p.Attrs {
		fmt.Fprintf(buf, " %s", attr)
	}
	if !p.IsUnnamed() {
		fmt.Fprintf(buf, " %s", p.Ident())
	}
	return buf.String()
}
```

So, for the proper fix, I guess we have to figure out essentially what attributes should be printed in which conditions, and see how this applies to our IR printing.

**Comment by dannypsnl** [comment]
https://llvm.org/docs/LangRef.html#i-call

> 5. The optional Parameter Attributes list for return values. Only ‘zeroext’, ‘signext’, and ‘inreg’ attributes are valid here.

> 10. ‘function args’: argument list whose types match the function signature argument types and parameter attributes. All arguments must be of first class type. If the function signature indicates the function accepts a variable number of arguments, the extra arguments can be specified.

LLParser.cpp(http://llvm.org/doxygen/LLParser_8cpp_source.html):
```cpp
 /// ParseParameterList
 ///    ::= '(' ')'
 ///    ::= '(' Arg (',' Arg)* ')'
 ///  Arg
 ///    ::= Type OptionalAttributes Value OptionalAttributes
 bool LLParser::ParseParameterList(SmallVectorImpl<ParamInfo> &ArgList,
                                   PerFunctionState &PFS, bool IsMustTailCall,
                                   bool InVarArgsFunc) {
   if (ParseToken(lltok::lparen, "expected '(' in call"))
     return true;
 
   while (Lex.getKind() != lltok::rparen) {
     // If this isn't the first argument, we need a comma.
     if (!ArgList.empty() &&
         ParseToken(lltok::comma, "expected ',' in argument list"))
       return true;
 
     // Parse an ellipsis if this is a musttail call in a variadic function.
     if (Lex.getKind() == lltok::dotdotdot) {
       const char *Msg = "unexpected ellipsis in argument list for ";
       if (!IsMustTailCall)
         return TokError(Twine(Msg) + "non-musttail call");
       if (!InVarArgsFunc)
         return TokError(Twine(Msg) + "musttail call in non-varargs function");
       Lex.Lex();  // Lex the '...', it is purely for readability.
       return ParseToken(lltok::rparen, "expected ')' at end of argument list");
     }
 
     // Parse the argument.
     LocTy ArgLoc;
     Type *ArgTy = nullptr;
     AttrBuilder ArgAttrs;
     Value *V;
     if (ParseType(ArgTy, ArgLoc))
       return true;
 
     if (ArgTy->isMetadataTy()) {
       if (ParseMetadataAsValue(V, PFS))
         return true;
     } else {
       // Otherwise, handle normal operands.
       if (ParseOptionalParamAttrs(ArgAttrs) || ParseValue(ArgTy, V, PFS))
         return true;
     }
     ArgList.push_back(ParamInfo(
         ArgLoc, V, AttributeSet::get(V->getContext(), ArgAttrs)));
   }
 
   if (IsMustTailCall && InVarArgsFunc)
     return TokError("expected '...' at end of argument list for musttail call "
                     "in varargs function");
 
   Lex.Lex();  // Lex the ')'.
   return false;
 }
```

So, I think the problem is the `metadata` have another rule for it, I would find how to fix it this night if possible.
```cpp
     if (ArgTy->isMetadataTy()) {
       if (ParseMetadataAsValue(V, PFS))
         return true;
     } else {
       // Otherwise, handle normal operands.
       if (ParseOptionalParamAttrs(ArgAttrs) || ParseValue(ArgTy, V, PFS))
         return true;
     }
```

**Comment by justinclift** [comment]
Awesome @dannypsnl, will try this out. :smile:

**Comment by justinclift** [comment]
Hmm, testing if it's metadata might work for other cases, but isn't working for this one. :frowning:

The LLVM IR my code is attempting to generate is:

```
define i8* @memset(i8* nocapture returned) {
entry:
call void @llvm.dbg.value(metadata i8* %0)
```

The code being used to create it:

```
p0 := ir.NewParam("", types.I8Ptr)
p0.Attrs = []ir.ParamAttribute{enum.ParamAttrNoCapture, enum.ParamAttrReturned}
memSetFunc := m.NewFunc("memset", types.I8Ptr, p0)
block := memSetFunc.NewBlock("entry")
call0 := block.NewCall(llvmdbgvalue, &metadata.Value{Value: p0})
```

When the `String()` code runs for the `p0` param, it's set out like this:

Breakpoint
Frame values

The `p` is a PointerType, as that's what the Parameter is.  It has no awareness it's being wrapped inside a `metadata.Value{}` for this function call.

So, the `!isMetadataType` check doesn't work, and the `nocapture returned` is included anyway.

Next ideas? :smile:

**Comment by justinclift** [comment]
Interestingly, looking up the frame stack a bit we can see that the Call itself does get passed the param's as metadata.  Look at `inst` → `Args` → `0` on the right side here.  It's clearly of the `metadata.Value` type:

Further up the call stack


The code which runs this section is here:

Corresponding code

Corresponding to this: https://github.com/llir/llvm/blob/c5c443dc6bf6217b0b5619d4f242e373dc3c6977/ir/inst_other.go#L395-L400

The only idea that's really coming to mind at the moment, is to have the metadata check there instead, and if it is then use an alternative way to print the string, which doesn't include the parameter attributes?

**Comment by justinclift** [comment]
Hmmm, adding an optional boolean parameter to the `String` method (to control attribute printing) would probably be overkill.  Wouldn't it?

**Comment by justinclift** [comment]
Having some real trouble getting this figured out, due to the layers of abstraction and interfaces. :frowning:

The [`Indent()` function for `metadata.Value`](https://github.com/llir/llvm/blob/c5c443dc6bf6217b0b5619d4f242e373dc3c6977/ir/metadata/metadata.go#L125-L128) can clearly see the type information for the value.  eg:

```
// Ident returns the identifier associated with the metadata value.
func (md *Value) Ident() string {
	fmt.Printf("%T", md.Value)  // <-- Added to print the type to stdout
	return md.Value.String()
}
```

This happily returns "`*ir.Param`" at the appropriate time.

The part I'm having trouble with, is figuring how to get switching on the type to work. eg:

```
switch md.Value.(type) {
case *ir.Param:
	fmt.Printf("foo")
}
```

Go just complains that `ir` is undefined, but trying to add it to the imports line instead has Go complaining about an imports cycle.  (side note, is it weird the compiler detect an import cycle and just stops, instead of dealing with it?)

Any ideas?  This is probably something basic, but I'm just not seeing it. :frowning:

**Comment by justinclift** [comment]
Gah, I can't figure this out.  Someone else is going to have to deal with it. :frowning:

**Comment by justinclift** [comment]
Because of the import cycle disallowing direct use of `ir`, this is an **extremely dodgy** workaround to remove the unwanted attribute names: https://github.com/justinclift/llir-llvm/commit/641512008e8e2802affc732e75219805dae4b5cd

In short, it checks the runtime representation of the type, and if it matches "*ir.Param" then it manually strips out selected works from the list.

On one hand... it's functional.

On the other hand... ugh.

It also turns out there are other places in the output .ll that the function attributes are appearing, when they shouldn't be (not due to my dodgy patch).  eg:

```
%5 = getelementptr inbounds i8, i8* nocapture returned %0, i32 %3
ret i8* nocapture returned %0
```

We'll probably need to take a different approach completely.

Instead, we should probably be adding the function attributes to the string when it's part of a function definition, and not any other time.

Thoughts?

**Comment by justinclift** [comment]
Going with the simple approach, this seems to solve both #88 and the problems here, as it only allows the "nonnull" attribute through: https://github.com/justinclift/llir-llvm/commit/7647122a7ee9f8f061e095610f80916a408a13f0

```
if _, isMetadataType := p.Type().(*types.MetadataType); !isMetadataType {
	for _, attr := range p.Attrs {
		buf.WriteRune(' ')
		buf.WriteString(attr.String())
		s := attr.String()
		if s == "nonnull" {
			buf.WriteRune(' ')
			buf.WriteString(s)
		}
	}
}
```

It's "good enough" for now. :wink:

**Comment by dannypsnl** [comment]
https://github.com/llir/llvm/pull/90#issuecomment-500380658 I think you can use your fork first since this PR seems not so easy to figure it out without any hardcoded.

https://github.com/llir/llvm/pull/90#issuecomment-500285744 In this case, the problem would be `*ir.Param` do not get enough information to make a decision, maybe a type assertion can solve it, just not sure how many places we have to do this, I think the problem is because of LLVM IR do not keep consistent at here, bring some weird solution. But anyway, I think I would try type assertion one.

**Comment by dannypsnl** [comment]
@mewmew I have a question, can we have a callee is not `*ir.Func`? Because at `inst_other.go` it's stored as `value.Value`

**Comment by justinclift** [comment]
Yeah, this has turned out to be trickier than expected. :wink:

**Comment by dannypsnl** [comment]
According to [reference](https://llvm.org/docs/SourceLevelDebugging.html#llvm-dbg-value), the prototype of `llvm.dbg.value` is `void @llvm.dbg.value(metadata, metadata, metadata)`, I think we can check callee parameter to decide how to print argument actually

**Comment by justinclift** [comment]
My brain is fried at the moment from having to dig into this too much.  Probably can't be useful for at least a few hours. :frowning:

**Comment by dannypsnl** [comment]
```
define i8* @memset(i8* nocapture returned) {
entry:
        call void @llvm.dbg.value(metadata i8* %0)
        ret void
}

declare void @llvm.dbg.value(metadata)
```
I add an interface for it, but I believe the solution is super ugly, anyway I push it first

**Comment by justinclift** [comment]
Interesting idea.  That could work.

I'll try it out later, or tomorrow and see how it goes. :smile:

**Comment by justinclift** [comment]
As a data point, I came across another LLVM IR line that needs the "nonnull" attribute added to it as well:

    %2 = call i32 @resource_write(i32 %1, i8* nonnull %stackalloc, i32 1)

That one is on a named BitCast though.  eg created using [`Block.NewBitCast()`](https://github.com/llir/llvm/blob/c5c443dc6bf6217b0b5619d4f242e373dc3c6977/ir/block_conversion.go#L122-L128).

**Comment by mewmew** [comment]
> @mewmew I have a question, can we have a callee is not *ir.Func? Because at inst_other.go InstCall it's stored as value.Value

@dannypsnl Yes. For instance, you can call an [ir.InlineAsm](https://godoc.org/github.com/llir/llvm/ir#InlineAsm) expression.

**Comment by dannypsnl** [comment]
https://github.com/llir/llvm/pull/90#issuecomment-500394882

I think this would be a new issue because we do not store attributes in **bit cast**, so maybe **call** should check it's parameters to decide how to generate it

**Comment by justinclift** [comment]
> I think this would be a new issue because we do not store attributes in bit cast, so maybe call should check it's parameters to decide how to generate it

Yeah, after noticing it I started thinking maybe we need to take a different approach completely. :smile:

**Comment by dannypsnl** [comment]
Test code:
```go
package ir

import (
	"github.com/llir/llvm/ir/enum"
	"github.com/llir/llvm/ir/types"
	"testing"
)

func TestBug(t *testing.T) {
	m := NewModule()
	f := m.NewFunc("main", types.Void)
	block := f.NewBlock("")
	alloc0 := block.NewAlloca(types.I8)
	bc0 := block.NewBitCast(alloc0, types.I8Ptr)
	bc0.LocalName = "stackalloc"
	load0 := block.NewLoad(bc0)
	p2 := NewParam("", types.NewPointer(types.I8))
	p2.Attrs = []ParamAttribute{
		enum.ParamAttrNonNull,
	}
	resourcewrite := m.NewFunc("resource_write", types.Void,
		NewParam("", types.I32),
		p2,
	)
	block.NewCall(resourcewrite, load0, bc0)

	block.NewRet(nil)

	println(m.String())
}
```

**Comment by mewmew** [comment]
Closing this issue, as mentioned in https://github.com/llir/llvm/issues/88#issuecomment-528566167

**Pull request closed without merging**
