### PR TITLE
there are some revive rules didn't match real need so I disable it

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

**Comment by dannypsnl** [comment]
@mewmew Maybe we should separate CI flow into testing and linting? Then we can handle both better. I also want to introduce the configuration of linter, therefore, the local lint won't get a different result than CI get.

**Comment by mewmew** [comment]
> @mewmew Maybe we should separate CI flow into testing and linting? 

Yes, we definitely should! Would you like to look into it?

As for this PR. I would prefer if we did not introduce any lint specific "special" comments to the source code. Having perfect linting is not the goal, the goal with linters is for them to suggest fixes. But when there are fixes we don't care about, we can just ignore them.

So, if we separate the build and lint CI, we can just have the output of the lint CI as suggestions, and the build CI as proper failures.

What do you think?

Cheers,
Robin

**Comment by dannypsnl** [comment]
Sure, that would be better. I would look into it, maybe I can try GitHub Action as it's working better for multiple target?

**Comment by mewmew** [comment]
> Sure, that would be better. I would look into it, maybe I can try GitHub Action as it's working better for multiple targets?

Go for it! Our Travis integration is ancient. If you find something that works better, feel free. Perhaps Cricle CI instead of Travis? With GitHub Actions? I don't know what's best to use these days, so if you have a suggestion, I'd be happy to learn.

**Pull request closed without merging**
