### PR TITLE
ir: Add Parent field to Func for its parent module

### PR DESCRIPTION
**Pull request by mewmew**
This is to be consistent with `ir.Block` which already contains a `Parent` field for its parent function, and to enable further use cases of the IR API (for background, see https://github.com/llir/llvm/issues/86#issuecomment-498959908).

cc: @pwaller and @justinclift

### CODE REVIEW

**Comment by pwaller** [comment]
Oh dear, CI is unhappy.

**Comment by mewmew** [comment]
> Oh dear, CI is unhappy.

Ah, that is to be expected. Since on of the examples (which is also run by `go test`) pretty-prints the IR structure, and we just added a new field to `ir.Func`.

**Comment by mewmew** [comment]
The CI for Go 1.11 now completes successfully. For Go tip, we get the following error:

```
The command "go get -u github.com/golangci/golangci-lint/cmd/golangci-lint" failed and exited with 1 during .
```

**Comment by mewmew** [comment]
Since the PR is rather non-invasive and the CI for Go 1.11 is happy, I'll go ahead and merge this.

**Pull request merged**
