### PR TITLE
asm/lexer: Use binary search for keyword lexing

### PR DESCRIPTION
**Pull request by quarnster**
benchmark                old ns/op   new ns/op   delta
BenchmarkParseString     85488       69866       -18.27%

### CODE REVIEW

**Comment by mewmew** [comment]
Beautiful! I had forgotten that the `sort` package provided binary search functions. I am handing in the project this week (finishing up the dissertation right now), so will take a closer look on Friday :)

**Comment by quarnster** [comment]
Good luck! :)

One addition I thought of afterwards was to just have it as `var keywords []string` and then in the `init` function fill it in by walking over `token.Keywords`. That way you only have one list to maintain and the other is automatically updated.

**Comment by mewmew** [comment]
> One addition I thought of afterwards was to just have it as var keywords []string and then in the init function fill it in by walking over token.Keywords. That way you only have one list to maintain and the other is automatically updated.

That is a really good idea! I was initially apprehensive to duplicate the defined keywords from the `token` package, as it would duplicate the work of updating the keywords later.

Oh, and thanks! I've mentioned you in the report :) Hope that is ok.

**Comment by quarnster** [comment]
You're welcome, and I do look forward to continuing to follow this project and perhaps help out here and there. All our communication has been public here so I see no harm in being mentioned in your report :)

**Comment by mewmew** [comment]
Thanks! I have really appreciated our discussions so far, and however you wish to be involved with this project in the future, it makes me happy to have more people on the team :) My aim is continue developing this library over the next year or so until it reaches production quality. To magically create time for development, I have applied for a couple of Uni units related to compiler development.

>  All our communication has been public here so I see no harm in being mentioned in your report :)

I was using the same reasoning when including your name, whereas private conversations have been anonymized.

**Comment by mewmew** [comment]
Hi Fredrik,

Now I've handed in the dissertation, and it feels just amazing! I want to merge this pull request and apply the changes you suggested (e.g. populate `keywords` by iterating over `token.Keywords` during `init`).

It seems that I cannot merge this pull request through GitHub (*We can’t automatically merge this pull request.*). I think this may have been my fault as I messed up a commit and had to re-push it. Therefore is seems like the hash of the optimize commit differs from your fork and this repo (llir/llvm@c517e9ef6e85476d910605bd67624d6f29ee45a6 and quarnster/llvm@dfb9d5129ffa2314acf6ea93fae9a5c617d5fd02).

Do you think you could sync with the latest version of the repo, so I can merge the pull request? Feel free to include the changes you mentioned (i.e. populate `keywords` from `token.Keywords`) if you feel like it. Otherwise I will submit that change in a follow-up commit.

**Comment by mewmew** [comment]
P.S. just in case you are interested and considering your name was mentioned in the report, here is a link to the PDF:
https://raw.githubusercontent.com/mewpaper/decompilation/master/decompilation.pdf

**Comment by quarnster** [comment]
Did a rebase and had to do a forced push to make anything happen, but think it should be mergeable now. Didn't get a chance to look at the token.Keywords addition nor your report yet.

**Comment by mewmew** [comment]
Thanks! This time it worked to merge the pull request. I have my last essay deadline today, so may get a chance to look at the token.Keywords afterwards. That is if you don't beat me to it :)

**Comment by mewmew** [comment]
Now I've submitted the change which populates keywords from token.Keywords during init. Thanks for the suggestion!

**Comment by mewmew** [comment]
Hej Fredrik,

How are you? I hope you are well, as I haven't heard from you since last autumn.

Me and a friend of mine are currently implementing a compiler for a subset of C. It's been a happy adventure and we will soon start looking at generating LLVM IR from the semantically verified parse tree.

I would like to ask you if we may reuse the code you wrote to optimize the LLVM IR lexer, as our lexer for C runs into the [exact same performance bottleneck](https://github.com/mewmew/uc/blob/bb746a5a1e01b63c047fc0c3c9855446d20dff1d/hand/lexer/state.go#L317).

Both of these projects [mewmew/uc](https://github.com/mewmew/uc) and [llir/llvm](https://github.com/llir/llvm) have been released into the public domain. We would therefore like to ask if you may consider to release your contribution into the public domain as well.

Hope to hear back from you.

Glada hälsningar -Robin

**Comment by mewmew** [comment]
@quarnster For public reference, would you be alright with releasing your contribution into the public domain? The intention is to keep the code of the [llir project released into the public domain](https://github.com/llir/llvm#public-domain), to simplify license handling for end users.

Haven't heard from you in a while? How is life nowadays? Hope you have been enjoying the warmth of spring in Sweden :)

Cheers /u

**Pull request merged**
