### PR TITLE
CI: switch to GitHub Action

### PR DESCRIPTION
**Pull request by dannypsnl**
* independent run coverage, linter, and test
* linter will only check without breaking test now
* test on more platforms: macOS, ubuntu. And more Go version: 1.12, 1.13, and 1.14

### CODE REVIEW

**Comment by mewmew** [comment]
Great job! Looks good to me. Would it be possible to have a dedicated run for Build? That was we could have successful build status, but failing test cases.

**Comment by mewmew** [comment]
I think we need to update the CI script to also clone the repository recursively. At least if we want for it to also test the testcases in `llir/testdata`.

Currently `go test` completes very quickly (which means it didn't run all tests):

From https://github.com/llir/llvm/pull/143/checks?check_run_id=631725008
```
Run go test ./...
go: finding github.com/google/go-cmp v0.3.1
go: finding github.com/kr/pretty v0.1.0
go: finding github.com/kr/text v0.1.0
ok  	github.com/llir/llvm/asm	0.013s
?   	github.com/llir/llvm/asm/enum	[no test files]
?   	github.com/llir/llvm/cmd/l-tm	[no test files]
ok  	github.com/llir/llvm/internal/enc	0.015s
?   	github.com/llir/llvm/internal/gep	[no test files]
ok  	github.com/llir/llvm/internal/natsort	0.002s
?   	github.com/llir/llvm/internal/osutil	[no test files]
ok  	github.com/llir/llvm/ir	0.005s
ok  	github.com/llir/llvm/ir/constant	0.004s
?   	github.com/llir/llvm/ir/enum	[no test files]
ok  	github.com/llir/llvm/ir/metadata	0.004s
ok  	github.com/llir/llvm/ir/types	0.004s
?   	github.com/llir/llvm/ir/value	[no test files]
```

**Comment by mewmew** [comment]
Also. Now, we can update the build badge of the readme to point to GitHub actions instead of Travis.

**Comment by dannypsnl** [comment]
I think once we add command: ”git submodule update --init” can fix that
problem. And I finally know why coverage I see yesterday is 27% xd.

Robin Eklind <notifications@github.com>於 2020年4月30日 週四，上午9:41寫道：

**Pull request merged**
