### PR TITLE
(#93) fix: add size check && fix variadic parameters

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

**Comment by dannypsnl** [comment]
@mewmew Sorry about that, but I didn't fix the logic bug about `if err != nil`, could you revert the commit first?

**Comment by mewmew** [comment]
> @mewmew Sorry about that, but I didn't fix the logic bug about if err != nil, could you revert the commit first?

No worries. I can submit a follow-up commit to fix the `if err != nil` logic. I liked your solution of adding a formatted I/O writer for keeping the change to a minimum. I'll break out this functionality, document it a bit and add it to the `helper.go` source file.

Cheers,
Robin

**Comment by dannypsnl** [comment]
Got it, thanks.

**Comment by mewmew** [comment]
> Got it, thanks.

Commited in 293cf9ae11e26afd202bb15c56a08c14214538b1.

**Pull request merged**
